[package]
name = "komari"
version = "0.1.0"
authors = ["AkiraFukushima <h3.poteto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
